# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fansub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MALMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.PositiveIntegerField(unique=True)),
                ('synoms', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('alternative_title', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaTorrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.CharField(blank=True, max_length=20, null=True)),
                ('format', models.CharField(blank=True, max_length=10, null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torrents.Anime')),
                ('fansub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torrents.Fansub')),
                ('mal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torrents.MALMeta')),
            ],
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.TextField(unique=True)),
                ('url', models.URLField()),
                ('download_url', models.URLField()),
                ('download_magnet', models.TextField(null=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torrents.MetaTorrent')),
            ],
        ),
    ]
