# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrent',
            name='data',
        ),
        migrations.AddField(
            model_name='metatorrent',
            name='torrent',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='torrents.Torrent'),
            preserve_default=False,
        ),
    ]
