# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 13:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0002_auto_20160509_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 10, 13, 44, 35, 33521, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 10, 13, 44, 38, 361279, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fansub',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 10, 13, 44, 41, 336932, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fansub',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 10, 13, 44, 43, 473211, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='malmeta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 10, 13, 44, 46, 177215, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='malmeta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 10, 13, 44, 48, 617271, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metatorrent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 10, 13, 44, 51, 433266, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metatorrent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 10, 13, 44, 54, 217113, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
