# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0003_auto_20160510_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torrent',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='torrent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 10, 13, 45, 33, 448700, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='torrent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 10, 13, 45, 37, 312913, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
