# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0004_auto_20160510_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torrent',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AddField(
            model_name='anime',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
