# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0006_auto_20160510_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AddField(
            model_name='malmeta',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='malmeta',
            name='synonyms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='malmeta',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
