# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0007_auto_20160510_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='malmeta',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
