# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0008_malmeta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fansub',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
