# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 17:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0009_fansub_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 11, 17, 32, 33, 586557, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
