# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fansub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MALMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.PositiveIntegerField(unique=True)),
                ('synoms', models.TextField()),
                ('image', models.URLField()),
                ('alternative_title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MetaTorrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.CharField(max_length=20, null=True)),
                ('format', models.CharField(max_length=10, null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torrents.Anime')),
                ('fansub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torrents.Fansub')),
                ('mal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='torrents.MALMeta')),
            ],
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.TextField(unique=True)),
                ('url', models.URLField()),
                ('download_url', models.URLField()),
                ('download_magnet', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='metatorrent',
            name='torrent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='torrents.Torrent'),
        ),
    ]
