# vim: set fileencoding=utf-8 :

MAL_ANIMES = {
'Hundred':("Hundred", "31338"),
"Seisen Cerberus Ryukoku no Fatalite":("Cerberus",'32595'),
"ReZero kara Hajimeru Isekai Seikatsu":("Re:Zero kara Hajimeru Isekai Seikatsu","31240"),
"Kidou Senshi Gundam UC RE0096":("Mobile Suit Gundam Unicorn RE:0096","32792"),
"Terraformars Revenge": ("Terra formars Revenge","31430"),
"JoJo's Bizarre Adventure Diamond is Unbreakable":("JoJo no Kimyou na Bouken: Diamond wa Kudakenai","31933"),
"Kagewani Shou":("Kagewani: Shou","32682"),
"The World God Only Knows Tenri Arc":("Kami nomi zo Shiru Sekai: Tenri-hen","15117"),
"The World God Only Knows 4 People and an Idol": ("Kami nomi zo Shiru Sekai: 4-nin to Idol","10805"),
"The World God Only Knows Four People and an Idol": ("Kami nomi zo Shiru Sekai: 4-nin to Idol","10805"),
"Kami nomi zo Shiru Sekai: 4-nin to Idol":("Kami nomi zo Shiru Sekai: 4-nin to Idol","10805"),
"Yozakura Quartet Hoshi no Umi": ("Yozakura Quartet: Hoshi no Umi","8457"),
"Wizard Barristers Benmashi Cecil":("Wizard Barristers: Benmashi Cecil","20053"),
"Rozen Maiden Zuruckspulen": ("Rozen Maiden: Zurückspulen","18041"),
"AKB0048 VOL III": ("AKB0048","12149"),
"AKB0048 VOL I & II": ("AKB0048","12149"),
"Buddy Complex Kanketsu-hen Ano Sora ni Kaeru Mirai de":("Buddy Complex: Kanketsu-hen - Ano Sora ni Kaeru Mirai de","24469"),
"Code Geass Boukoku no Akito 1": ("Code Geass: Boukoku no Akito 1 - Yokuryuu wa Maiorita", "8888"),
"Dungeon ni Deai o Motomeru no wa Machigatteiru Darou":("Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka","28121"),
"Fairy Tail Houou no Miko":("Fairy Tail Movie 1: Houou no Miko - Hajimari no Asa","17535"),
"Fate kaleid liner Prisma Illya": ("Fate/kaleid liner Prisma☆Illya","14829"),
"Fate kaleid liner Prisma Illya OVA":("Fate/kaleid liner Prisma☆Illya 2wei! OVA","26057"),
"Fate stay night":("Fate/stay night","356"),
"Fate stay Night Unlimited Blade Works":("Fate/stay night: Unlimited Blade Works","22297"),
"Fate Stay Night Unlimited Blade Works":("Fate/stay night: Unlimited Blade Works","22297"),
"Yozakura Quartet Tsuki ni Naku":("Yozakura Quartet: Tsuki ni Naku","18499"),
"Yowamushi Pedal The Movie":("Yowamushi Pedal Movie", "30413"),
"Yowamushi Pedal Re Road":("Yowamushi Pedal: Re:ROAD", "30790"),
"Yowamushi Pedal Re Ride": ("Yowamushi Pedal: Re:RIDE", "25755"),
"LUPIN THE 3rd": ("Lupin III", "1412"),
"Shonen Ashibe Go! Go! Goma-chan": ("Shounen Ashibe: Go! Go! Goma-chan", "32571"),
"Sousei no Onmyougi": ("Sousei no Onmyouji", "32105"),
"Yamishibai Japanese Ghost Stories 3":("Yami Shibai 3rd Season", "31994"),
"TERRAFORMARS REVENGE": ("TERRA FORMARS REVENGE","31430"),
"Showa Genroku Rakugo Shinju": ("Shouwa Genroku Rakugo Shinjuu", "28753"),
"Osomatsu san": ("Osomatsu-san","31174"),
"Gate Jieitai Kanochi nite, Kaku Tatakaeri":("Gate: Jieitai Kanochi nite, Kaku Tatakaeri","28907"),
"Gate Jietai Kanochi nite, Kaku Tatakaeri":("Gate: Jieitai Kanochi nite, Kaku Tatakaeri","28907"),
"Gate Jieitai Kanochi nite, Kaku Tatakaeri – Enryuu-hen":("Gate: Jieitai Kanochi nite, Kaku Tatakaeri","28907"),
u'Gate Jieitai Kanochi nite, Kaku Tatakaeri \u2013 Enryuu-hen':("Gate: Jieitai Kanochi nite, Kaku Tatakaeri","28907"),
"Kidou Senshi Gundam Tekketsu no Orphans": ("Mobile Suit Gundam: Iron-Blooded Orphans","31251"),
"Nurse Witch KOMUGI R": ("Nurse Witch Komugi-chan R","31890"),
"BBKBRNK":("Bubuki Buranki","32023"),
"Monster Musume no Iru Nichijou Vol":("Monster Musume no Iru Nichijou","30307"),
"Seto no Hayanome":("Seto no Hanayome","2104"),
"Kono Danshi Maho Ga Oshigoto Desu":("Kono Danshi, Mahou ga Oshigoto Desu","31815"),
"Kono Subarashii Sekai ni Shukukufu wo!'":("Kono Subarashii Sekai ni Shukufuku wo!","60553"),
"Kono Subarishii Sekai ni Shufukufu wo!'":("Kono Subarashii Sekai ni Shukufuku wo!","60553"),
"Plastic Memories Vol":("Plastic Memories",""),
"Tabimachi Lateshow":("Tabi machi Late show",""),
"Onsen Yosei Hakone-chan":("Onsen Yousei Hakone-chan",""),
"Working!!! SP":("Working!!!",""),
"Gochumon wa Usagi Desu":("Gochuumon wa Usagi Desu",""),
"Tonari no Seki kun":("Tonari no Seki-kun",""),
"Kamisama Hajimemahita":("Kamisama Hajimemashita",""),
"Tamaidou Gakuen":("Taimadou Gakuen 35 Shiken Shoutai",""),
"Valkyrie Drive Mermaid":("Valkyrie Drive: Mermaid",""),
"Hokuto no Ken 2 et Hokuto no Ken Ichigo Aji":("DD Hokuto no Ken 2 Ichigo Aji+",""),
"ONE-PUNCH-MAN":("ONE PUNCH MAN",""),
"Kindaichi Shounen no Jikembo Returns": ("Kindaichi Shounen no Jikenbo Returns",""),
"Gekijouban Card Captor Sakura":("Cardcaptor Sakura Movie 2: The Sealed Card",""),
"Mahou Shoujo Madoka Magica Rebellion":("Mahou Shoujo Madoka★Magica Movie 3: Hangyaku no Monogatari",""),
"Monogatari Series Second Season":("Monogatari Series",""),
"Rebuild of Evangelion 1-3":("Rebuild of Evangelion",""),
"The World God Only Knows Tenri-hen":("Kami nomi zo Shiru Sekai: Tenri-hen",""),
"Gekijouban Mahou Shoujo Madoka Magica 1-2":("Gekijouban","62671"),
"Gekijouban Mahou Shoujo Madoka":("Gekijouban","62671"),
"Nekomonogatari Shiro": ("Nekomonogatari",""),
" Memories Off 2nd & 5 ":("Memories Off" ,""),
"Mahou Shoujo Madoka Magica Hajimari no Monogatari":("Mahou Shoujo Madoka★Magica Movie 1: Hajimari no Monogatari","11977"),
"Vampire Hunter D 1985 &":("Vampire Hunter D",""),
"Kokoro Connect Batch":("Kokoro Connect",""),
"Jormungand Batch":("Jormungand",""),
"Kamijigen Game Neptune PP":("Choujigen Game Neptune The Animation",""),
"To Aru Kagaku no Railgun S":("Toaru Kagaku no Railgun",""),
"Haiyoru! Nyaruani Remember My Love":("Haiyoru! Nyaruani: Remember My Love(craft-sensei)",""),
u'C\xb3 Cube x Cursed x Curious':("Cube","10578"),
"Baby Princess 2D Paradise 0":("Baby Princess 3D Paradise",""),
"To Aru Kagaku no Railgun OVA":("Toaru Kagaku no Railgun",""),
}

BYPASS = [
"Nietzsche",
"Ultraman",
"Mabushii OST",
]

RELEASE_GROUPS = [
"ShinGureZora",
"Mabushii",
"Hoshizora",
"Mezazora",
"EaS",
"HEZ",
"EagleZora",
]
